### ISSUE TITLE
Icon/Logo

### ISSUE THREAD

**Issue by digitalcoyote** [digitalcoyote/NuGetDefense#11]
An icon or logo helps to associate a "brand" and makes the project more identifiable on other platforms. 

Not a priority, but I'm open to any contributions.

**Comment by laurinerichonnier** [comment]
Hi! I can help you to create a logo if you want.

**Comment by digitalcoyote** [comment]
@laurinerichonnier as long as you are OK with licensing it in a way it can be distributed/used with this project without restrictions. Contributions are welcome and appreciated.
