### ISSUE TITLE
sonatype-2019-0115 reported for jQuery @ 3.6.3, but not on ossindex.sonatype.org

### ISSUE THREAD

**Issue by git-hub-user** [digitalcoyote/NuGetDefense#125]
**Describe the bug**
Currently, I get two build errors for jQuery:
```
- error : 1 vulnerabilities found for jQuery @ 3.6.3
- 8>C:\projects\CRIos\src\CRIos.Backend\packages.config(4,4): error : OSS Index ID: sonatype-2019-0115 : 1 non-CVE vulnerability found. To see more details, please create a free account at https://ossindex.sonatype.org/ and request for this information using your registered account
```

**To Reproduce**
1. Create a new solution of type _ASP.NET application_ and select _MVC_ and _framework 4.8_
1. Open the _NuGet Package Manager_
1. Apply all _Updates_
    * This will currently update jQuery from 3.4.1 to 3.6.3
1. Install _NuGetDefense_
    * 3.0.10 is installed
1. Build All
    * The Reported build errors are generated

**Expected behavior**
0 vulnerabilities reported for jQuery.

**Tools (please complete the following information):**
 - IDE: VS2022 Professional 17.5.1
 - OS: Microsoft Windows [Version 10.0.19044.2604]

**Additional context**
I am not sure if this is an issue with NuGetDefense or with sonatype, but the build errors are not consistent with the information found on https://ossindex.sonatype.org/:
1. https://ossindex.sonatype.org/component/pkg:npm/jquery reports `This version of jquery has no known vulnerabilities!`
1. https://ossindex.sonatype.org/vulnerability/sonatype-2019-0115 shows a link to https://github.com/jquery/jquery/pull/4333, which was merged to `jquery:master` on on Mar 25, 2019 and thus has been released with jQuery 3.4.0.

Notes:
- sonatype does not list jQuery under NuGet, but under npm. I do not know if that has any implication on the functioning of NuGetDefense.
- jQuery.Validation @ 1.19.5 is also reported with these reproduction steps. I left it out of scope.

**Comment by digitalcoyote** [comment]
It looks like there is still a vulnerable in the nuget package as described in https://github.com/OSSIndex/vulns/issues/289 
It does seem to depend on the usage of a bundled file and not jquery itself though.
