### ISSUE TITLE
Question: Where is the default cache location?

### ISSUE THREAD

**Issue by afrischk** [digitalcoyote/NuGetDefense#127]
I don't find any documentation on where to find the default cache location or the NVD database?

Can you please help me with this? Thanks!

**Comment by digitalcoyote** [comment]
I'll have to code dive to be sure, but I believe the cache is disabled unless a path is specified. The NVD database is embedded in the package (wherever that is stored) and updated in place.

I'll try to get back with you when I get a chance to verify the cache location. I'll try to update the docs site with appropriate info as well.

**Comment by digitalcoyote** [comment]
Sorry about the delay, Family Events and a little overtime pushed this back. It currently uses the underlying sqlLite lib's behavior for when the path isn't specified. Per documentation, this causes it to use a temporary on disk file. So it's effectively disabled if you don't specify a path. 

This needs to be corrected. Is there anywhere you'd prefer to use as a default location? I'm thinking it will likely be the same directory used for the NuGetDefense.json file unless someone has a better place for it to exist. I'm not fond of the possibility of ending up in source control or making people add an ignore pattern for it, so I'm open to suggestions.

**Comment by afrischk** [comment]
Hey, no worries!

For other tools I see the default localtion somewhere in `C:\Users\<username>\AppData\Local` on windows or in a dot-folder under `/home/<username>/` on linux. So I would be fine with that.

In my opinion documentation is key here even if you don't plan to change something. Would also be fine for me :-)

**Comment by digitalcoyote** [comment]
The new default location is released v3.1.1 I have not documetented everywhere that maps to (but I'd like to). I'm going to open a separate documetnation issue to map where the NuGetDefense folder is on various operating systems.  I think it's fairly standard across linux distros, but it could vary based on env variables.
