### ISSUE TITLE
Does not create settings file

### ISSUE THREAD

**Issue by explunit** [digitalcoyote/NuGetDefense#147]
**Describe the bug**
The documentation says that it will create the settings file on first run, but it does not. 

**To Reproduce**
1. Run this command `NugetDefense --solution .\MySolution.sln --nugetdefense-json NugetDefense.json`

**Expected behavior**
Expected it to create a settings file.

**Screenshots**

results in an error like this:
`: Error : Encountered a fatal exception while load settings. Exception: System.IO.FileNotFoundException: Settings file not Found!`

Omitting the `--nugetdefense-json` part it still does not create the file anywhere.

**Tools (please complete the following information):**
 - OS: Powershell 7

**Additional context**

Version 3.2.0-prerelease3

**Comment by digitalcoyote** [comment]
Should be fixed in the latest prerelease, I'll reopen after I have the chance to test this in a fresh environment if it is  still failing. I hope to finish up the issues in the pre-releases soon and get those released in a stable version before expanding on the new NVD functionality.
