### ISSUE TITLE
NuGetDefence.lib: json report file not showing the list fo vulnarable packages

### ISSUE THREAD

**Issue by chiluap** [digitalcoyote/NuGetDefense#154]
After scanning the json report file does show the number of affected packages, but the list of issues is empty.

**To Reproduce**
1. scan a project with issues configuring json repotfile:
```json
{
 "VulnerabilityReports": {
    "OutputTextReport": false,
    "JsonReportPath": "./TestResults/DependencyErrors.json"
  }
}
```
2. the repotfile looks like this:
```json
{
  "VulnerabilitiesCount": 11,
  "Packages": []
}
```

**Expected behavior**
Packages array to not be empty.

**Comment by digitalcoyote** [comment]
Sorry this took so long, should be available as soon as indexing is done on NuGet.org
