### ISSUE TITLE
Fatal Exception - System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by xtbmedia** [digitalcoyote/NuGetDefense#156]
### **Describe the bug**
Tool crashes with a fatal System.ArgumentException when reading from the cache.

### **To Reproduce**
1. Run the tool, ensuring some vulnerabilities are added to the cache
2. Re-run the tool, with the same configuration settings. When reading data from the cache the above exception will be thrown.

### **Expected behavior**
No exception to be thrown, vulnerability scan to complete.

#### **IDE**
Microsoft Visual Studio Enterprise 2022
Version 17.7.4
VisualStudio.17.Release/17.7.4+34031.279
Microsoft .NET Framework
Version 4.8.09032

#### **OS**
Windows 11 (22H2 - 22621.2283)

### **Additional context**
![image](https://github.com/digitalcoyote/NuGetDefense/assets/48799818/49dcb94c-89ba-4236-abf8-048ff1863ff1)

**Comment by xtbmedia** [comment]
I have a fix for this which I will submit a PR for (probably tomorrow).

**Comment by digitalcoyote** [comment]
Thank you very much. My day job has a pretty big workload at the moment so I haven't had time to even finish the changes I've been working on.

I'll prioritize reviewing and merging the PR once you have it ready.

**Comment by xtbmedia** [comment]
Well that took longer than expected!
