### ISSUE TITLE
Problem with .Net 8 and NugetDefense 4

### ISSUE THREAD

**Issue by ByteDecoder** [digitalcoyote/NuGetDefense#172]
**Describe the bug**
Seems the nugetdefense. targets for version 4.0.0 are set for net.6.0 instead of .net 8 and the building project/solution fails.

Environment:
.Net 8.0.101
NugetDefense 4.0.0

**To Reproduce**
- Build a project using .net 8 and NugetDefense 4.0.0

**Expected behavior**
- Should compile without any errors of incorrect .net versioning

**Tools (please complete the following information):**
 - IDE: [VSCODE]
 - OS: [Windows 11 Home 23H2 build 22631.3007]

**Additional context**
Changing in the nugetdefense.target in the nuget package solves the issue compiling with .net 8

From 6.0 
`
<NuGetDefenseExe Condition="'$(OS)' == Unix">dotnet "$(MSBuildThisFileDirectory)../tools/net6.0/NuGetDefense.dll"</NuGetDefenseExe>
        <NuGetDefenseExe Condition="'$(OS)' == 'Windows_NT'">dotnet "$(MSBuildThisFileDirectory)..\tools\net6.0\NuGetDefense.dll"</NuGetDefenseExe>
`

To 8.0

`<NuGetDefenseExe Condition="'$(OS)' == Unix">dotnet "$(MSBuildThisFileDirectory)../tools/net8.0/NuGetDefense.dll"</NuGetDefenseExe>
        <NuGetDefenseExe Condition="'$(OS)' == 'Windows_NT'">dotnet "$(MSBuildThisFileDirectory)..\tools\net8.0\NuGetDefense.dll"</NuGetDefenseExe>
`

**Comment by digitalcoyote** [comment]
If you want to submit a PR, I'll merge it. Or I'll hopefully get to it later tonight.

Thanks for bringing that up.

**Comment by digitalcoyote** [comment]
pushing 4.0.0.1 out shortly
