### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by natan-abolafya** [digitalcoyote/NuGetDefense#176]
**Describe the bug**
Hello. We're getting this error after upgrading 3.2.0 to 3.2.1.
```
......csproj : error : Encountered a fatal exception while checking for Dependencies in ......csproj. Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options)
......csproj: Error : Encountered a fatal exception while checking for Dependencies in .....csproj. Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options)
```

I tried to get more information but adding the following to NuGetDefense.json made no difference:
```
  "Log": {
    "LogLevel": "Debug"
  }
```
I can try again if you let me know what mistake I have made.

**To Reproduce**
1. Have our project structure and dependencies that I can't share here
2. Upgrade from 3.2.0 to 3.2.1 and try to build project.

**Expected behavior**
Build not to fail.

**Tools (please complete the following information):**
 - IDE: Currently happens on CI and a bit of work to find out the details. Maybe this is useful? `MSBuild version 17.8.3+195e7f5a3 for .NET`
 - OS: Happens on linux (various docker images for various distributions) and macOS builds but not on Windows. But the projects for those are slightly different, so it might be due to a different dependency for example.

**Comment by digitalcoyote** [comment]
I'll see about reproducing this. I mainly use NuGetDefense on Linux but I haven't personally run 3.2.1 yet. I'll try to look into this tonight or tomorrow.

If you can share a project file this occurs on, it will speed up the investigation (all I really need in it are the package references). 

Also, are you using the NuGetDefense.Tool package or NuGetDefense?

**Comment by natan-abolafya** [comment]
This is from the main csproj
```
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <PackageReference Include="INIFileParserDotNetCore" Version="2.5.2" />
    <PackageReference Include="Mono.Unix" Version="7.1.0-final.1.21458.1" />
    <PackageReference Include="Pkcs11Interop" Version="5.1.2" />
    <PackageReference Include="NuGetDefense" Version="3.2.1" />
  </ItemGroup>
```

And this is Shared.csproj
```
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StreamJsonRpc" Version="2.17.11" />
  </ItemGroup>
```

**Comment by digitalcoyote** [comment]
Work has been crazy (12hr days trying to push a project through). I'm going to try to debug this later today. Which means a fix would likely go out tomorrow.

Sorry about the delay in looking into it.

**Comment by digitalcoyote** [comment]
Rebuilding the NVD Global data before I debug, somehow I wiped it after the last version was published

**Comment by digitalcoyote** [comment]
@natan-abolafya If v4.0.2 or v3.2.2  doesn't resolve the issue, feel free to reopen this, but I was able to reproduce the error so this should resolve it.
