### ISSUE TITLE
3.2.4: System.Exception: Invalid dotnet list output. Run `dotnet restore` then build again.

### ISSUE THREAD

**Issue by natan-abolafya** [digitalcoyote/NuGetDefense#180]
**Describe the bug**
Upgrading from 3.2.3 to 3.2.4 breaks a couple of our builds with the following message:
   ..................csproj : error : Encountered a fatal exception while checking for Dependencies in .......csproj. Exception: System.Exception: Invalid dotnet list output. Run `dotnet restore` then build again.

.NET Version: 8.0.202
OS: 
- Android build on Ubuntu 22:04 docker image
- macOS build on macOS 13.5.1

**Comment by digitalcoyote** [comment]
I've seen that a few times since early in 3.x. typically rerunning the build success, but I'm not sure yet why the dotnet list is failing when we already run a dotnet restore in our CI beforehand.

If this is easily reproducable I'll try to get some logging together to see what it's getting from dotnet list that's problematic.

**Comment by natan-abolafya** [comment]
I tried rebuilding first, the result was the same. Note that our linux builds were fine. Can't test Windows due to #95 :). I'll be happy to collect more logs if you tell me how.

**Comment by digitalcoyote** [comment]
I'll put some logging together tonight. We have only run into this on Windows so that's at least some helpful info.

There's a unit test I use to make sure past issues with dotnet list parsing don't reocur. If it's not intermittent, you could try running one with the output from `doynet list --inclide-transitive`

**Comment by natan-abolafya** [comment]
On first attempt, it failed with this error:
> No assets file was found for `.......csproj`. Please run restore before running this command.

Then I added a `dotnet restore` command first. Now the build passes. Should that be required? I thought `dotnet build` would take care of it.

**Comment by natan-abolafya** [comment]
yeah, failed after I bumped to 3.2.4. `dotnet list` output looks the same.

**Comment by digitalcoyote** [comment]
Version 3.2.4.1-issue180 should log out the output of `dotnet list` that NuGetDefense is trying to parse. If it's not more than 3 lines it's assumed that it failed or had no packages returned.

Give that a try and share that part of the lot if you can. If you can't, details about the first 3-4 lines may be enough to figure out what's happening.

**Comment by natan-abolafya** [comment]
this is all I could find:
```
   ...../AndroidClient.csproj : error : Encountered a fatal exception while checking for Dependencies in ...../AndroidClient.csproj. Exception: System.Exception: Invalid dotnet list output. Run `dotnet restore` then build again.
         at NuGetDefense.Core.NuGetFile.ParseListPackages(String dotnetListOutput)
         at NuGetDefense.Core.NuGetFile.dotnetListPackages(String projectFile, String targetFramework, Dictionary`2& projectectReferencePackages)
        at NuGetDefense.Core.NuGetFile.LoadPackages(String targetFramework, Boolean checkTransitiveDependencies, Boolean checkReferencedProjects)
         at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options)
```

**Comment by digitalcoyote** [comment]
That makes me think it didn't get any output from the command. Interesting... I'll dig more into this after work today. I may need to rework how it's running dotnet list and getting the output.

**Comment by digitalcoyote** [comment]
If you're ok with ignoring transitive dependencies I can put a build up that ignores that error until I have a better idea of why it's not reading the output of the command properly.

**Comment by natan-abolafya** [comment]
We could stay at 3.2.3 for now I think. So there is no rush. But thanks.

**Comment by digitalcoyote** [comment]
I've had a few unexpected issues with trying to parse dotnet list. I'm going to try parsing the project.assets.json file instead and deprecate this method. With any luck that will be a much easier to debug as well.

**Comment by digitalcoyote** [comment]
I'll have a release soon that I believe will fix this. If not I'll reopen it.

**Comment by digitalcoyote** [comment]
Haven't had time to test it in our CI yet. Hoping to get to that tomorrow.

**Comment by digitalcoyote** [comment]
2nd prerelease out and a stable version with an improvement for the dotnet list parsing that should improve reliabiltiy a little. I apparently forgot about F# and VB.Net for a moment when I coded that.

**Comment by natan-abolafya** [comment]
that seems to have solved the problem. Thank you!
