### ISSUE TITLE
bootstrap 4.4.1 still reporting vulnerabilities after updating

### ISSUE THREAD

**Issue by dahlsailrunner** [digitalcoyote/NuGetDefense#24]
**Describe the bug**
Vulnerabilities reported when I have updated version to be past the known vulnerabilities list.

**To Reproduce**
I just had bootstrap 3.4.1 in the project, saw vulnerabilities (good), and then updated from 3.4.1 to 4.4.1 -- the vulnerabilities persisted (bad -- I think).
![image](https://user-images.githubusercontent.com/8389867/80035347-7c71c800-84b5-11ea-8bd7-5016b1084164.png)

**Expected behavior**
I would have expected the vulnerabilities on bootstrap to go away.  The packages.config shows "bootsrap" (lower case b) and the vulnerabilities show Bootstrap, and I'm not sure if that makes a difference.

Let me know if I have misinterpreted results.

**Tools (please complete the following information):**
 - IDE: Vs 2019
 - OS: Win 10

**Additional context**

**Comment by dahlsailrunner** [comment]
If I added "bootstrap" to the ignored pacakges, the warnings go away properly.

**Comment by digitalcoyote** [comment]
While investigating this I found a problem in the deserialization. I'll be investigating it further before moving forward with this. 

It appears there is a problem in the NVD Source with properly checking the version. I'll be looking into this. tomorrow if I can sleep (got up after 2 hours to look at the json issue)

**Comment by dahlsailrunner** [comment]
That's great - and I really appreciate it.  Bootstrap might not be the most common package to be using via NuGet (most would grab it via npm) but I'm guessing some older projects may still have the nuget ref.  Fixing in 1.0.6 is fine with me.

**Comment by digitalcoyote** [comment]
It looks like the versions array for those vulnerabilities included a wildcard. I'm debugging now to make sure that the parsing of the vulnerabilities from NVD is working correctly. Debugging requires letting it run through all of the vulnerabilities in the source, so this may take a bit.

**Comment by dahlsailrunner** [comment]
Really appreciate the review on this.  Thanks a ton.

**Comment by digitalcoyote** [comment]
I ran into some problems with hte myget feed due to  overall package size (was on free subscription). I'm going to go ahead and start pushing some test versions to NuGet as prerelease. If you want to check them out in the meantime, they should have better results for bootstrap). I'll be pushing 1.0.6 this weekend for sure even if this issue is not fully resolved, but I have a work-a-round  to fix specific parsing problems until I get a chance to work in a more permanent change.

**Comment by dahlsailrunner** [comment]
That's awesome - I'll have a look this weekend and let you know what I see.
