### ISSUE TITLE
Having a space in path returns code 532462766

### ISSUE THREAD

**Issue by marcopierobon** [digitalcoyote/NuGetDefense#26]
**Describe the bug**
Using a directory with a whitespace in the path, makes VS return code 532462766.

**To Reproduce**
1. Add a whitespace in the project path
2. Compile the rproject
3. Copy the command from the error window
4. Run the command from the console
5. The error will show as "Unhandled exception. System.IO.FileNotFoundException: Could not find file 'FILENAME_BEFORE_WHITESPACE'.

**Expected behavior**
The build should complete even with the whitspace

**Screenshots**

**Tools (please complete the following information):**
 - IDE: VS2017
 - OS: Windows

**Comment by digitalcoyote** [comment]
I'm starting a Dev-Feed for testing packages and I uploaded a package there that should fix your issue. I won't have time to test and release it until lunch (This is serious, common and simple to fix, so It's getting a priority boost ahead of earlier issues).

The issue appears to be that hte MSBuildProjectPath variable is not rapped in quotes (at least in .net core's msbuild).

 https://www.myget.org/F/nugetdefense-dev/api/v3/index.json

**Comment by digitalcoyote** [comment]
Should be in 1.0.6.0 when it releases (probably this weekend). If needed sooner comment to let me know.

**Comment by marcopierobon** [comment]
Perfect, man!
