### ISSUE TITLE
Set a User-Agent when communicating with OSS Index

### ISSUE THREAD

**Issue by DarthHater** [digitalcoyote/NuGetDefense#29]
**What is the Feature? Please describe.**

Hello! As someone who works on or around OSS Index, basically we'd love it if you could set a User-Agent when communicating with the service.

If you can read Golang, this package has a bunch of tests and code where we generate one:

https://github.com/sonatype-nexus-community/nancy/tree/master/useragent

If TypeScript is more your thing:

https://github.com/sonatype-nexus-community/auditjs/blob/master/src/Services/RequestHelpers.ts#L20-L26

**Use Case**

Essentially this lets us see a bit better how much your tool is calling OSS Index, and is not used for any nefarious purposes, just ultimately let's us know if we should maybe get more involved with helping on the tool, as well on how much effort we put into specific ecosystems related to the data.

**Describe alternatives you've considered**

Nothing really, this one is pretty cut and dried.

**Additional context**

Nothing, but we love that you made this tool, and appreciate you!

**Comment by digitalcoyote** [comment]
I'll try to get this into the next release of NuGetDefense.OSSIndex.

**Comment by digitalcoyote** [comment]
Added in 0eb28284ab16376c39f3d19d07d2c96f13697110
This will be released shortly in NuGetDefense as well
