### ISSUE TITLE
Authentication for OSS Index

### ISSUE THREAD

**Issue by digitalcoyote** [digitalcoyote/NuGetDefense#32]
**What is the Feature? Please describe.**
OSS Index has support for authentication that can be used to increase the rate limiting threshold 
**Use Case**
Users with many projects and/or frequent builds may hit rate limiting errors more often.

**Describe alternatives you've considered**
N/A, this is suggested by OSS Index

**Additional context**
https://ossindex.sonatype.org/doc/rest

**Comment by digitalcoyote** [comment]
Looks like I may be tackling this next. I have a test in CI (building [GitExtensions](https://www.nuget.org/packages/NuGetDefense/) in a GitHub Action) that fails due to sending too many requests to OSS Index on one of the last projects. GitExtensions includes over 30 projects.

Adding authentication feels more like a bandage than providing a solution to that problem. I'm looking for a better way to handle this long term (especially for larger solutions that may hit the authenticated limit as well).

**Comment by domai86** [comment]
Hey, just feedback: I'm really looking forward to this, since I'm hitting the limit in our solution.

**Comment by digitalcoyote** [comment]
I'm hitting it as well in the CI test build for GitExtensions. I'm looking into an alternative setup using the dotnet tool to scan multiple projects at once and making a single call to OSSIndex. If authentication doesn't raise the limit enough, that may be an alternative.

**Comment by digitalcoyote** [comment]
This did less for my use case than I expected. I've read on other projects that the limit for requests with authentication is 64 requests per hour. Since NuGetDefense runs it's test builds all at once, I rapidly exceed this limit. Solutions for this generally seem to be results for specific packages and using up one of your 64 calls if you have recently checked all packages in your call. My earlier idea was to allow the dotnet tool variant of NuGetDefense to scan all projects in a solution/folder (recursive search) at once, but in a CI setup, that could still easily exceed the limit if a lot of builds are being done or if you have several solutions.

**Comment by digitalcoyote** [comment]
I did something really stupid. I only added the credentials to one of the two modes that can be used to query OSSIndex.  I've corrected this and it should be in the CI soon. If that Passes, I'll release it with documentation following (hopefully) shortly.

**Comment by digitalcoyote** [comment]
Released in [v1.0.10](https://github.com/digitalcoyote/NuGetDefense/releases/tag/v1.0.10)
