### ISSUE TITLE
Request to output findings to text file

### ISSUE THREAD

**Issue by jwilliamson1** [digitalcoyote/NuGetDefense#33]
**What is the Feature? Please describe.**
Apologies in advanced if I missed something, but I wanted to know if there is a way to output the results of a finding, positive or negative to a text file. Perhaps just having a field in the NugetDefense.json like:
`output: "myfile.txt"`
As a way of keeping audit trail of findings.
**Use Case**
The use would be for a way to look at previous builds in a ci/ci pipeline and see if there was any issues.

**Describe alternatives you've considered**
I had considered parsing the output of the failure, but I thought might ask to see if something like this already exists.

**Additional context**

**Comment by jwilliamson1** [comment]
Closing as I saw Gitter is the prefered way to ask questions.

**Comment by digitalcoyote** [comment]
Reopening to track request.

**Comment by digitalcoyote** [comment]
I'm using [Serilog](https://serilog.net/) to allow defining one or more log files (and eventually other sinks).

 @jwilliamson1 if you have any preference on format, let me know. I intend to make the template string for Serilog configurable eventually, but if you have a preference, I'll start with that. I'm aiming to have an early version of this out this weekend and then expand it more later on.

**Comment by digitalcoyote** [comment]
Early look at the configuration for the Log:

> {
  "WarnOnly": false,
  "Log": {
    "OutPut": "ReportedVulnerabilities.log",
    "LogLevel": 2,
    "RollingInterval": 0
  },
  "CheckTransitiveDependencies": true,
  "ErrorSettings": {
    "ErrorSeverityThreshold": 5,
    "CVSS3Threshold": -1,
    "IgnoredPackages": [
      {
        "Id": "NugetDefense",
        "Version": "1.0.8.0"
      }
    ],
    "IgnoredCvEs": []
  },
  "OssIndex": {
    "Enabled": true,
    "BreakIfCannotRun": true
  },
  "NVD": {
    "SelfUpdate": false,
    "TimeoutInSeconds": 15,
    "Enabled": true,
    "BreakIfCannotRun": true
  }
}

**Comment by jwilliamson1** [comment]
Hi! Thanks for looking at this. We use this xml format that Trivy supplies. It uses a junit template. Something like that would be ideal, but any output is good.
[https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/junit.tpl](url)

"
<?xml version="1.0"?>
-<testsuites>
-<testsuite name="your-image-path" time="" failures="1" tests="1">
-<properties>
<property name="type" value="your-os-distro"/>
</properties>
-<testcase name="[HIGH] CVE-Number" time="" classname="the-package-that-is-failing">
<failure type="description" message="the-package-name: the failure message."</failure>
</testcase>
</testsuite>
</testsuites>
"

**Comment by digitalcoyote** [comment]
@jwilliamson1 Would either of these work for you: 


[ExampleReports.zip](https://github.com/digitalcoyote/NuGetDefense/files/5159065/ExampleReports.zip)

I tried to vaguely follow the template you linked while at the same time, getting something that should be "easily readable" and generic enough for general use. There are also separate logs in the latest build.

**Comment by digitalcoyote** [comment]
A couple methods of doing this have been added in [v1.0.8](https://github.com/digitalcoyote/NuGetDefense/releases/tag/v1.0.8). Feel free to reopen this or comment if any other formats are required. I hope to get docs updated soon.
