### ISSUE TITLE
OSS Index Package Limit

### ISSUE THREAD

**Issue by digitalcoyote** [digitalcoyote/NuGetDefense#37]
**Describe the bug**
OSS Index does not allow scanning more than 128 packages at a time

**To Reproduce**
1. Have a project with more than 128 packages and NuGetDefense.
2. Build

**Expected behavior**
Sends 128 packages at a time
**Error Message**
{"code":400,"message":"Request for more than 128 components"}

**Tools (please complete the following information):**
 - IDE: Azure Function CLI
 - OS: Win 10 Latest

**Additional context**
Was building an Azure Function and hit this problem. 
First I've seen of this error.

**Comment by digitalcoyote** [comment]
I need to fix this in order to finish my other work, so this should be up fairly soon. Anyone encountering this can use the SensitivePackages Feature to limit the number of packages that are sent up for now.

**Comment by digitalcoyote** [comment]
Fixed in[ v1.0.4](https://github.com/digitalcoyote/NuGetDefense.OSSIndex/releases/tag/v1.0.4)

**Comment by sp-stefan** [comment]
I am having the same issue with today's date...

"b'{"code":400,"message":"Request for more than 128 components"}'"

**Comment by digitalcoyote** [comment]
@sp-stefan I'll take a look into this once I get back today but a couple of details will make the investigation faster:

- What version of NuGetDefense are you using?
- Are you using the CLI or the NuGetDefense package?
- If the solution is open source, which is it (I'll debug against that project specifically if available)

Also, to prevent this from stopping your build, you can set OSSIndex source's BreakIfCannotRun to false like this (assuming all other settings are defaults):

`{
  "WarnOnly": false,
  "VulnerabilityReports": {
    "OutputTextReport": true
  },
  "CheckTransitiveDependencies": true,
  "CheckReferencedProjects": false,
  "ErrorSettings": {
    "ErrorSeverityThreshold": "any",
    "Cvss3Threshold": -1,
    "IgnoredPackages": [
      {
        "Id": "NugetDefense"
      }
    ],
    "IgnoredCvEs": [],
    "AllowedPackages": [],
    "WhiteListedPackages": [],
    "BlockedPackages": [],
    "BlacklistedPackages": []
  },
  "OssIndex": {
    "ApiToken": "",
    "Username": "",
    "Enabled": true,
    "BreakIfCannotRun": false
  },
  "GitHubAdvisoryDatabase": {
    "ApiToken": "",
    "Username": "",
    "Enabled": true,
    "BreakIfCannotRun": false
  },
  "NVD": {
    "SelfUpdate": false,
    "TimeoutInSeconds": 15,
    "Enabled": true,
    "BreakIfCannotRun": true
  },
  "SensitivePackages": []
}
`
