### ISSUE TITLE
OSS Index scan failed on updating NugetDefense package to any version higher than 1.0.7.2

### ISSUE THREAD

**Issue by jollynv** [digitalcoyote/NuGetDefense#39]
**Describe the bug**
Below error is thrown on compiling the project after updating the NugetDefense package  to any version higher than 1.0.7.2

error : NuGetDefense : OSS Index scan failed with exception: System.NullReferenceException: Object reference not set to an instance of an object.
at NuGetDefense.OSSIndex.ComponentReportVulnerability.ToVulnerability()

**Expected behavior**
No error should be thrown on compiling.

**Screenshots**

**Tools (please complete the following information):**
 - IDE:  VS2019
 - OS: Windows 10 pro

**Additional context**

**Comment by digitalcoyote** [comment]
Just got back from a funeral, will probably be tomorrow before I can look into this. Are you able to provide a list of packages installed and the target framework? I have an idea where that might be coming from, but those will make it easier to debug if I need to.

**Comment by jollynv** [comment]
Target Framework: .NET Core 3.1
Screenshot of packages:
![image](https://user-images.githubusercontent.com/72568327/95579621-7f418480-0a25-11eb-9aa5-7240771fe5ee.png)
There are more packages installed in the projects that are referenced by the main project. Do you need the list of those packages too?

**Comment by digitalcoyote** [comment]
I was able to get an aggregate exception, but not a null reference. I'll keep digging and add some null checking I assumed was redundant. I've hit my limit for the hour on OSSIndex calls running unit tests.

**Comment by digitalcoyote** [comment]
I believe I've identified the issue. When you get a chance, try [v1.0.13](https://www.nuget.org/packages/NuGetDefense/1.0.13) It includes a fix for ToVulnerability that nullchecks the CVE and Attack Vector.

**Comment by jollynv** [comment]
The error is gone after updating the package to  v1.0.13. Thank you for fixing this quickly.
