### ISSUE TITLE
Warning that 0 vulnerabitilies was found

### ISSUE THREAD

**Issue by terkill** [digitalcoyote/NuGetDefense#41]
**Describe the bug**
When my projects depend an the Nancy nuget I get a warning that **0** vulnerabilities was found for Nancy

**To Reproduce**
1. Have a project depend on Nancy@2.0.0 ([Reproduction repo](https://github.com/terkill/NugetDefense.Nancy.Warning))
2. Enable the NVD Scanner
3. Build produces one warning "0 vulnerabilities found for Nancy @ 2.0.0"

**Expected behavior**
I would not expect any warning

**Screenshots**
-

**Tools (please complete the following information):**
 - IDE: VS2019
 - OS: Windows 10 Update 2004

**Additional context**
-

**Comment by digitalcoyote** [comment]
This should be fixed on the next release.This was a side effect of reworking the logging. If you need this urgently, I can build/release it. Otherwise I'm going to try to handle #40 first and release them together.

**Comment by terkill** [comment]
No urgency at all.
I will wait for the next release, thank you.

**Comment by digitalcoyote** [comment]
1.0.14-pre0001 should be published soon and contains a fix for this, I'm going to try to squeeze in one more issue before the final release

**Comment by digitalcoyote** [comment]
Should be fixed in [v1.0.14](https://github.com/digitalcoyote/NuGetDefense/releases/tag/v1.0.14). I encourage you to reopen this if this build does not fix the issue.
