### ISSUE TITLE
1.0.15 fails to build

### ISSUE THREAD

**Issue by blackchess12** [digitalcoyote/NuGetDefense#45]
**Describe the bug**
I tried upgrading my project to use NuGetDefense 1.0.15, however Visual Studio fails the build with the following error

```
MSB3073	The command "dotnet "C:\Users\auser\.nuget\packages\nugetdefense\1.0.15\build\..\tools\net5.0\NuGetDefense.dll" "C:\test\test\test.csproj" netcoreapp3.1" exited with code 1.	test	C:\Users\auser\.nuget\packages\nugetdefense\1.0.15\build\nugetdefense.targets	10	

1>------ Build started: Project: test, Configuration: Debug Any CPU ------
1>test -> C:\test\test\bin\Debug\netcoreapp3.1\test.dll
1>Could not execute because the specified command or file was not found.
1>Possible reasons for this include:
1>  * You misspelled a built-in dotnet command.
1>  * You intended to execute a .NET Core program, but dotnet-C:\Users\auser\.nuget\packages\nugetdefense\1.0.15\build\..\tools\net5.0\NuGetDefense.dll does not exist.
1>  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
1>C:\Users\auser\.nuget\packages\nugetdefense\1.0.15\build\nugetdefense.targets(10,5): error MSB3073: The command "dotnet "C:\Users\auser\.nuget\packages\nugetdefense\1.0.15\build\..\tools\net5.0\NuGetDefense.dll" "C:\test\test\test.csproj" netcoreapp3.1" exited with code 1.
1>Done building project "test.csproj" -- FAILED.
```

**To Reproduce**
1. Create a new .NET Core 3.1 project
2. Update project to use NuGetDefense 1.0.15
3. Build solution

**Expected behavior**
* The solution builds

**Tools (please complete the following information):**
 - .NET Version: netstandard2.0
 - IDE: Visual Studio Professional 2019 16.8.2
 - OS: Windows 10 OS Build 19042.630

**Additional context**
  - The previous NuGetDefense 1.0.14 builds successfully
  - I haven't installed the .NET 5 SDK

**Comment by digitalcoyote** [comment]
`..\tools\net5.0\NuGetDefense.dll` I'll need to rebuild it. Apparently I failed to change the command on the 1.x branch. Expect 1.0.15.1 to be up shortly.

**Comment by digitalcoyote** [comment]
- Delisted v1.0.15
- Updated Targets File in the 1.x branch
- Tested v1.0.15.1
- Packed and Uploaded
- Updated Release Asset with v1.0.15.1 instead of v1.0.15

Should be available shortyle

**Comment by blackchess12** [comment]
Thanks for the quick response. v1.0.15.1 resolved the issue for me.
