### ISSUE TITLE
Please Provide a Build Task Example

### ISSUE THREAD

**Issue by Torsten1981** [digitalcoyote/NuGetDefense#48]
Please Provide a Build Task Example for MSBUILD style project and sdk projects.
In documentation https://digitalcoyote.github.io/NuGetDefense/  it is mentioned that "NuGetDefense is a bundled dotnet tool that runs using an MSBuild ExecTask after your project finishes building."

But how to configure this build task? What are the correct values? Please find below my example that is not working (MSBUILD style - related to .NET 4.6.2 Fullframework project  )

```
<Target Name="AfterBuild">
	<UsingTask TaskName="NuGetDefense.Tool" AssemblyFile="C:\Users\{user}\.dotnet\tools\.store\nugetdefense.tool\2.0.2\nugetdefense.tool\2.0.2\tools\net5.0\any\NugetDefense.dll" />
	<NuGetDefense.Tool />
  </Target> 
```

**Comment by digitalcoyote** [comment]
@Torsten1981 if you are using the NuGetDefense package, it imports the build task automatically when installed in the package (AfterBuild). The dotnet tool was intended for CI use instead. 

This is what is bundled in the package:

```
<PropertyGroup>
    <NuGetDefenseExe Condition="'$(OS)' == Unix">dotnet "$(MSBuildThisFileDirectory)../tools/net5.0/NuGetDefense.dll"</NuGetDefenseExe>
    <NuGetDefenseExe Condition="'$(OS)' == 'Windows_NT'">dotnet "$(MSBuildThisFileDirectory)..\tools\net5.0\NuGetDefense.dll"</NuGetDefenseExe>
  </PropertyGroup>
  
  <Target Name="CheckForVulnerableNuGetPkgs" AfterTargets="Build">
    <Exec Command="$(NuGetDefenseExe) &quot;$(MSBuildProjectFullPath)&quot; $(TargetFramework)" IgnoreExitCode="false" />
  </Target>
```

**Comment by digitalcoyote** [comment]
Setting this to Hold for now as It's not the intended use of the nuget package and this issue has some examples that could be used until this makes it into the official documentation.

**Comment by digitalcoyote** [comment]
Closing as this was added to the docs site: https://digitalcoyote.github.io/NuGetDefense/docs/getting-started#net-global-tool-w-msbuild-task
