### ISSUE TITLE
Provide a NuGet package to do the check programmatically

### ISSUE THREAD

**Issue by RicoSuter** [digitalcoyote/NuGetDefense#49]
**What is the Feature? Please describe.**
I'm looking for a library where i can provide a list of package names and versions to a .NET method and get a list of the vulnerable packages. I think this should be easily doable by extracting the actual code into a e.g. NuGetDefinse.Core package.

**Use Case**
I want to leverage this library in https://apimundo.com in the NuGet package index and .NET project index.

**Comment by digitalcoyote** [comment]
I actually have 3 packages available for those that want to make similar tools. You may want to look at those and see if they meet your needs. 

# NuGetDefense.NVD contains the NVD scanning features.
# NuGetDefense.OSSIndex contains the logic for sending the packages to OSS Index to get vulnerabilities.

#NuGetDefense.Core is a dependency of both of these and contains a lot of the logic used in NuGetDefense that isn't related to settings, msbuild, or reporting.

If you need something added to these or moved out of NuGetDefense into Core or another package let me know and I'll see what I can do.

**Comment by RicoSuter** [comment]
Ah nice, didnt see that...

So for best security coverage I'd send my packages to NuGetDefense.NVD and NuGetDefense.OSSIndex? 
So there is no "aggregation" package like NuGetDefense where all "providers" are called and aggregated and maybe provides a bulk operation for better performance?

**Comment by digitalcoyote** [comment]
I'd be willing to throw something together after the holidays (I'll be focusing closing out the other open issues first). 

Let me know any specifics you need for your use case. My gut would tell me to have a function exposed that allows passing in a settings object (to enable the full set of  and an ienumerable of packages (with or without line/file data) and returns an array of vulnerabilities.

**Comment by digitalcoyote** [comment]
I've gotten crazy busy at work and I need to focus on other features when I have time to work on them. Additionally, any bugs will take priority over this. I need to refactor the main package to be able to do this, which will be a decent amount of work.

**Comment by RicoSuter** [comment]
No worries, maybe I'll look into this when I need it. Appreciate the work you're doing anyway.

**Comment by digitalcoyote** [comment]
A small update. I'm working on this being available as part of v3.x. The CLI Tool is getting an overhaul to support more use cases as well in that version. I currently don't anticipate it releasing until sometime after .Net 6 is released.

**Comment by digitalcoyote** [comment]
Took far too long, but the first preview of this is up. I expect to pull the arguments out of Scan and into a constructor instead (and perhaps expose a static method that jumps straight to the scan like it does now).

https://www.nuget.org/packages/NuGetDefense.Lib/3.0.0-pre0001
