### ISSUE TITLE
Use  .Net on Windows

### ISSUE THREAD

**Issue by digitalcoyote** [digitalcoyote/NuGetDefense#5]
Packing a .Net 4.8 version of the tool would remove the need for .Net Core 3.1 on Windows.

**Comment by digitalcoyote** [comment]
When .Net 5 becomes standard this should not be needed. PR's welcome if anyone wants to implement this before then.

**Comment by SimonCropp** [comment]
FYI i created a small string typed wrapper around ossindex that targets netstandard2.0 and netstandard2.1 https://github.com/SimonCropp/OssIndexClient

**Comment by digitalcoyote** [comment]
I'm splitting up the package so I can fork a windows only .Net 4.8 version. I don't feel like it's worth increasing the package size to include this when the current package is cross platform.

**Comment by digitalcoyote** [comment]
Closing this since .Net 5 is releasing in November and I'll consider packaging a special version later if someone doesn't want to install the .Net 5 sdk
