### ISSUE TITLE
Requesting Vulnerability Source `dotnet list package --vulnerable`

### ISSUE THREAD

**Issue by digitalcoyote** [digitalcoyote/NuGetDefense#60]
**Source**
https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/

**Why should this source be considered?**
It's probably going to be the go to source for most dev's

**Should this source be checked by default?**
yes

**Would this be better in an independent package?**
No

**Comment by digitalcoyote** [comment]
Getting the publish together. Will be fixed in v2.1.1 and v1.0.17

**Comment by rajbos** [comment]
Will this be an extra source for finding vulnerabilities that automatically can be ran? 
It would be a welcome addition since we cannot really use the dotnet list command as is in a CI/CD scenario without adding string comparison scripts around it. :-)

**Comment by digitalcoyote** [comment]
The current plan is to add the option to the 'dotnet list' command run internally by NuGetDefense.Core and parse out any vulnerabilities there (if it's enabled).

**Comment by digitalcoyote** [comment]
Did some research on this and it appears that it relies on a single source (github).  Looking into just adding that source as the information supplied from the DotNet tool is very limited and complicates DotNet list parsing
