### ISSUE TITLE
Figuring out several errors during a run of the dotnet tool

### ISSUE THREAD

**Issue by rajbos** [digitalcoyote/NuGetDefense#62]
**Describe the bug**
I'm seeing several errors / behaviors during a test run for the dotnet tool on our own code base. I wanted to debug these issues and attempt to help improve stuff I run into during this process, so I created this issue to link other things to in an effort to keep track of things. The goal is to improve the OOTB experience for other users.

**To Reproduce**
I ran the tool from the command line on our own project that I cannot share. Will try to debug things locally.

**Expected behavior**
A full scan with logs on it 😄 .

**Logs**

```
❯ nugetdefense .\****.sln Release
`dotnet list` Errors:

.\tests\****.Api.Tests\***.Api.Tests.csproj(18,6) : Warning : Unable to find a version for this package. It will be ignored.
`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

.\tests\***.Tests.Unit\***.Tests.Unit.csproj(13,6) : Warning : Unable to find a version for this package. It will be ignored.
`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

.\tests\****.Tests.Acceptance\****.Tests.Acceptance.csproj(30,6) : Warning : Unable to find a version for this package. It will be ignored.
`dotnet list` Errors:

Skipping dotnet list package. No Packages found for .\src\Results\Results.csproj.
`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

.\***.sln: Error : Encountered a fatal exception while checking for Dependencies in .\***.sln. Exception: System.AggregateException: One or more errors occurred. (Unable to read feeds from NVD)
 ---> System.Exception: Unable to read feeds from NVD
   at NuGetDefense.NVD.FeedUpdater.GetFeedsAsync()+MoveNext()
   at NuGetDefense.NVD.FeedUpdater.GetFeedsAsync()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NuGetDefense.NVD.Scanner.CreateNewVulnDataBin(String vulnDataFile)
   at NuGetDefense.NVD.Scanner.CreateNewVulnDataBin(String vulnDataFile)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NuGetDefense.NVD.Scanner..ctor(String nugetFile, TimeSpan vulnDataReaTimeout, Boolean breakIfCannotRun, Boolean selfUpdate)
   at NuGetDefense.Program.Main(String[] args) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense/Program.cs:line 144
```

**Tools (please complete the following information):**
NET 5.0 solution file

**Comment by rajbos** [comment]
Any idea where to find the origin of the message ` Warning : Unable to find a version for this package. It will be ignored.` ? 

Would like to know **which** package causes this 😁

**Comment by digitalcoyote** [comment]
> Any idea where to find the origin of the message ` Warning : Unable to find a version for this package. It will be ignored.` ?
> 
> Would like to know **which** package causes this

Line 129 of NugetFile.cs in NuGetDefense.Core

Sorry for that delay in response. Work had us return to the office and I've lost time and sleep do to the commute.

**Comment by rajbos** [comment]
Figured out that the message `Warning : Unable to find a version for this package. It will be ignored.` comes from a package that has a `*` in the version number:

````
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.*" />
```
