### ISSUE TITLE
Cannot find part of the path in a build after a clean git clone

### ISSUE THREAD

**Issue by rajbos** [digitalcoyote/NuGetDefense#63]
**Describe the bug**
In an effort to research things for issue #62, I found this behavior of the source code.
Build error after a clean git clone on the repo: Cannot find part of the path `NuGetDefense\Src\NuGetDefense\bin\Release\net5.0`. Building the release version will fix this

**To Reproduce**
1. git clone
2. open visual studio
3. build on the default `Debug` configuration

**Expected behavior**
A working build 😁 

**Screenshots**
-

**Tools (please complete the following information):**
 - IDE: VS2019
 - OS: Windows 10

Reason this error happens is because of the setting in `NuGetDefense\build\nugetdefense.targets`:
```
<Target Name="CheckForVulnerableNuGetPkgs" AfterTargets="Build">
    <Exec Command="$(NuGetDefenseExe) &quot;$(MSBuildProjectFullPath)&quot; $(TargetFramework)" IgnoreExitCode="false" />
  </Target>
```

Removing the exec command fixes things. I'm guessing here, but this is to run the tool itself after building? 

1. Not sure why this is running it against the delete output then? 
2. Not sure how to reset that to use the Debug config, since that is what is selected?

**Comment by digitalcoyote** [comment]
`NuGetDefense\build\nugetdefense.targets` shouldn't be imported as part of the build script for NuGetDefense itself. I did find a leftover copy of part of that file at the bottom of the NuGetDefense project file (now removed). the nugetdefense.targets is packed into the .nupkg to be imported by projects with the package installed. 

Pull the latest and let me know if that fixes it. If not, I'll fire up Windows and try a fresh checkout/build.

**Comment by rajbos** [comment]
Check, that helps. Wasn't sure why it was there.
