### ISSUE TITLE
Build NuGetDefense in Debug mode: cannot find file `bin/Release/net5.0/VulnerabilityData.bin`

### ISSUE THREAD

**Issue by rajbos** [digitalcoyote/NuGetDefense#64]
**Describe the bug**
Was trying to get things working in relation to #62 and the Vulnerability.bin is not there yet. Trying to follow the comment from this [issue #56](https://github.com/digitalcoyote/NuGetDefense/issues/56#issuecomment-786646469_) above for .NET 5.0 but more errors from it. 

**To Reproduce**
1. .git clone
2. get the build to find the release folder (see #63)
3. build again (in release config!)
4. Error cannot find file `bin/Release/net5.0/VulnerabilityData.bin`

Building things in Debug mode seems to work, although I still cannot find that file.
Switching back to Release mode then still works.

Seems to be related to the same target file as #62, removing that build step clears up the error.

**Expected behavior**
The build to work and download its own version of the file 😄 or a step in the readme on how to download it manually and copy it to the right location.

**Screenshots**
-

**Tools (please complete the following information):**
 - IDE: VS2019
 - OS: Windows 10

**Comment by digitalcoyote** [comment]
Generally I build NuGetDefense.NVD repo and use it to build the vulnerability data used by NuGetDefense. I'll look into this as soon as I get a chance. I am also expecting a documentation overhaul after I finish cleaning up the codebase (prepping for v3.x).

**Comment by rajbos** [comment]
Will try that!
