### ISSUE TITLE
Solution contains `vcxproj` projects, these also pull in nugets

### ISSUE THREAD

**Issue by Smurf-IV** [digitalcoyote/NuGetDefense#74]
**What is the Feature? Please describe.**
Mixed solution with `vcxproj` files, that are also pulling in nuget packages

**Use Case**
Scan those packages as well

**Describe alternatives you've considered**
WhiteSource Bolt

**Comment by digitalcoyote** [comment]
I'll try to take a look at this tonight. If you can throw together a minimal sample solution (or can point me to an open source one) it would help to kickstart things once I get to my desk.

**Comment by digitalcoyote** [comment]
I'm guessing that a vcxproj is a managed c++ project. I'm trying to figure out how to create one from Linux with Rider. If I have to boot into Windows, this will probably be put off til tomorrow (Windows updates).

**Comment by digitalcoyote** [comment]
@Smurf-IV  I tested NuGetDefense on a .vcxproj and it seemed to work as expected. Are you getting any unexpected errors? Or perhaps is there an issue with scanning referenced projects when the referenced project is a vcxproj?

**Comment by digitalcoyote** [comment]
I'm going to close this for now. Feel free to open a new issue or we can reopen this one if this ends up being an issue
