### ISSUE TITLE
Error scanning a solution that includes a wix project

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#76]
**Describe the bug**
Firstly the error line does not highlight which project the error occurred in, making investigation difficult. Secondly I get an error while scanning an entire solution. The output is:
: Error : Encountered a fatal exception while checking for Dependencies in . Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NuGetDefense.Scanner.LoadMultipleProjects(String TopLevelProject, String[] projects, Boolean specificFramework, String targetFramework, Boolean solutionFile) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 228
   at NuGetDefense.Scanner.Scan(ScanOptions options) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 60

**To Reproduce**
1. From a command window run nugetdefense --solution "MySolution.sln"

**Expected behavior**
Output of vulnerable NuGet packages referenced by projects in the solution

**Additional context**
Version in use is 3.0.1+c0cbebf66c9c875d0c8beda90a3b8881aa7268cc

**Comment by a-teece** [comment]
Update on this is that debugging using source shows the issue is with the wixproj file which is part of the solution. The error is when accessing the monikers array because ProjectTargets has 0 entries in it.
                var monikers = proj.ProjectTargets.Select(t => t.Moniker).ToArray();
                monikersListBuilder.Append(monikers[0]);

What is weird is that directly running the scan on the wixproj file doesn't crash.

**Comment by digitalcoyote** [comment]
Thanks for the bug report and taking an initiative on it. I usually like to start looking into these right after work, but I've got to do some server maintenance tonight so it will probably be tomorrow before I can actively setup a wix project and look into it. I'd also be willing to review and merge a PR if you feel like working it yourself. 

Thanks again.

**Comment by a-teece** [comment]
I'll try and find time to do a fix and send you a PR. Think I've found another (as-yet-undefined) issue too so i'll poke that a little more
