### ISSUE TITLE
Exception when OSSIndex is disabled or fails to update

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#77]
**Describe the bug**
A "object reference not set to an instance of an object" exception is thrown if OSS Index is disabled but GitHub Advisory is enabled due to an attempt to merge the dictionaries together while one of them is null.

**To Reproduce**
1. Disable OSSIndex, Enable GitHub Advisory Index

**Expected behavior**
No error

**Comment by digitalcoyote** [comment]
Fixed in v3.0.2 via PR #78
