### ISSUE TITLE
Old style projects are not parsed correctly

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#79]
**Describe the bug**
Old-style projects use a namespace for the PackageReference, and include the version in an XML Node instead of an XML Element. This causes the check in the Core project to skip calling dotnet list for these projects because it thinks there are 0 packages, incorrectly.

**To Reproduce**
1. Scan an "old-style" project that includes a namespace on the <Project> node:
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="15.0">

**Expected behavior**
The list of packages is correctly extracted

**Comment by digitalcoyote** [comment]
Fixed in v3.0.2 via PR [#3](https://github.com/digitalcoyote/NuGetDefense.Core/pull/3) on NuGetDefense.Core
