### ISSUE TITLE
Incorrect warning message when running on Windows

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#80]
**Describe the bug**
On Windows platforms the message "`dotnet list` Errors: {errorOutputBuilder}" is incorrectly output to the console window due the a blank line being 2 chars (CR and LF) instead of just 1.

**To Reproduce**
1. Run the CLI on a Windows machine

**Expected behavior**
The message is only output when the process error output is > Environment.NewLine.Length rather than a hard coded 1

**Comment by digitalcoyote** [comment]
Fixed in v3.0.2 via PR [#3](https://github.com/digitalcoyote/NuGetDefense.Core/pull/3) on NuGetDefense.Core
