### ISSUE TITLE
` instead of ' seems to be littered through the code base

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#81]
**Describe the bug**
I would not expect warning messages to a console nor exceptions to include a `. .net standard exceptions always use ' and I would expect any library to follow the same approach.

**Expected behavior**
Only use ' in exceptions and messages to logs/console

**Comment by digitalcoyote** [comment]
Not sure how this happened, but I'm not against correcting it. If it doesn't cause any direct issues, I'll add the Hacktoberfest label and someone can grab it then if they'd like.

**Comment by a-teece** [comment]
Many years ago when I was a young programmer I searched for 2 days for a un-reproducible bug around this. It was because my end-user had copied something via email and Outlook was helpful and turned ' into a "pretty" `

**Comment by digitalcoyote** [comment]
It looks like this is no longer an issue. The uses of `  (backtick)  in powershell scripts are done because it's the escape character for powershell. Usages in markdown files are done because they have special usage there as well.
