### ISSUE TITLE
Warn only option is forced to on

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#83]
**Describe the bug**
The warn only option is forced to true (even when false in settings) if no vulnerability CvssScore > cvss3Threshold. This is a bug in VulnerabilityReporter.BuildVulnerabilityTextReport

**To Reproduce**
1. Leave cvss3Threshold as -1
2. Add Microsoft.ChakraCore 1.11.23 to a project
3. Run a scan

**Expected behavior**
Exit code != 0 due to a vulnerability

**Comment by digitalcoyote** [comment]
Fixed in v3.0.3 via PR #84
