### ISSUE TITLE
Missing ConfigFile leads to ExitCode > 0

### ISSUE THREAD

**Issue by ChristopherThiedeVireq** [digitalcoyote/NuGetDefense#89]
**Describe the bug**
If SettingsFile is set but SettingsFile does not exists or can not be loaded ExitCode is 1. This ExitCode 1 can not be differed from NumberOfVulnerabilities.

**To Reproduce**
Run NuGetDefense with Option --nugetdefense-json with not existing config file.

**Expected behavior**
ExitCode is < 0

**Tools (please complete the following information):**
 - IDE: VS2022
 - OS: Windows 10

**Comment by digitalcoyote** [comment]
I'll see about getting this fixed tonight unless you'd like to submit a PR yourself. Thanks for the report!

**Comment by ChristopherThiedeVireq** [comment]
I add a PR with some refactoring (clean code) and fix the issue. But the build failed. I don't know how to fix the build failure.
