### ISSUE TITLE
packages without vulnerablities are in Report

### ISSUE THREAD

**Issue by ChristopherThiedeVireq** [digitalcoyote/NuGetDefense#93]
**Describe the bug**
Each Package with or without Vulnerabilities is in the report. Packages without Vulnerabilities has an empty Vulnerabilities-Property.

**Expected behavior**
packages without Vulnerabilities are not shown in report.

**Tools (please complete the following information):**
 - IDE: VS2022

**Comment by ChristopherThiedeVireq** [comment]
Hi again.
I add a Pull Request.
Kind regards
Chris

**Comment by digitalcoyote** [comment]
I'll see about getting this published tonight or tomorrow.

**Comment by digitalcoyote** [comment]
Fixed in v3.0.7 by #94
